repos:
  # Dockerfile
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
  # shell
  - repo: local
    hooks:
      # shellcheck
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
      # shfmt
      - id: shfmt
        name: shfmt
        entry: shfmt
        args: ["-w", "-s"]
        language: system
        types: [shell]
        require_serial: true
  # python
  - repo: local
    hooks:
      # pytest
      - id: pytest
        name: pytest
        entry: uv run --no-active pytest tests
        language: python
        types_or: [python, pyi]
      # ruff lint
      - id: ruff-lint
        name: ruff-lint
        entry: uv run ruff check
        language: python
        types_or: [python, pyi]
        require_serial: true
      # ty check
      - id: ty
        name: ty
        entry: uv run ty check
        language: python
        types_or: [python, pyi]
        require_serial: true
      # mypy
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: python
        types_or: [python, pyi]
        require_serial: true
      # ruff format
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: python
        types_or: [python, pyi]
        require_serial: true
