repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Dockerfile
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
  # shell
  - repo: local
    hooks:
      # shfmt
      - id: shfmt
        name: shfmt
        entry: shfmt
        args: ["-w", "-s"]
        language: system
        types: [shell]
        require_serial: true
      # shellcheck
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
  # python
  - repo: local
    hooks:
      - id: ruff-formatter
        name: ruff-formatter
        entry: ruff format
        language: python
        types_or: [python, pyi]
        require_serial: true
      # ruff lint
      - id: ruff-lint
        name: ruff-lint
        entry: ruff check
        args: ["--fix"]
        language: python
        types_or: [python, pyi]
        require_serial: true
      - id: ty
        name: ty
        entry: ty check
        language: python
        types_or: [python, pyi]
